/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { ServiceClientOptions } from "@azure/ms-rest-js";
import * as msRest from "@azure/ms-rest-js";

/**
 * Reference to another subresource.
 */
export interface SubResource {
  /**
   * Resource ID.
   */
  id?: string;
}

/**
 * IP configuration of an Azure Firewall.
 */
export interface AzureFirewallIPConfiguration extends SubResource {
  /**
   * The Firewall Internal Load Balancer IP to be used as the next hop in User Defined Routes.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly privateIPAddress?: string;
  /**
   * Reference to the subnet resource. This resource must be named 'AzureFirewallSubnet' or
   * 'AzureFirewallManagementSubnet'.
   */
  subnet?: SubResource;
  /**
   * Reference to the PublicIP resource. This field is a mandatory input if subnet is not null.
   */
  publicIPAddress?: SubResource;
  /**
   * The provisioning state of the Azure firewall IP configuration resource. Possible values
   * include: 'Succeeded', 'Updating', 'Deleting', 'Failed'
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly provisioningState?: ProvisioningState;
  /**
   * Name of the resource that is unique within a resource group. This name can be used to access
   * the resource.
   */
  name?: string;
  /**
   * A unique read-only string that changes whenever the resource is updated.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly etag?: string;
  /**
   * Type of the resource.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly type?: string;
}

/**
 * Public IP Address associated with azure firewall.
 */
export interface AzureFirewallPublicIPAddress {
  /**
   * Public IP Address value.
   */
  address?: string;
}

/**
 * IpGroups associated with azure firewall.
 */
export interface AzureFirewallIpGroups {
  /**
   * Resource ID.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly id?: string;
  /**
   * The iteration number.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly changeNumber?: string;
}

/**
 * Public IP addresses associated with azure firewall.
 */
export interface HubPublicIPAddresses {
  /**
   * The list of Public IP addresses associated with azure firewall or IP addresses to be retained.
   */
  addresses?: AzureFirewallPublicIPAddress[];
  /**
   * The number of Public IP addresses associated with azure firewall.
   */
  count?: number;
}

/**
 * IP addresses associated with azure firewall.
 */
export interface HubIPAddresses {
  /**
   * Public IP addresses associated with azure firewall.
   */
  publicIPs?: HubPublicIPAddresses;
  /**
   * Private IP Address associated with azure firewall.
   */
  privateIPAddress?: string;
}

/**
 * Properties of the AzureFirewallRCAction.
 */
export interface AzureFirewallRCAction {
  /**
   * The type of action. Possible values include: 'Allow', 'Deny'
   */
  type?: AzureFirewallRCActionType;
}

/**
 * Properties of the application rule protocol.
 */
export interface AzureFirewallApplicationRuleProtocol {
  /**
   * Protocol type. Possible values include: 'Http', 'Https', 'Mssql'
   */
  protocolType?: AzureFirewallApplicationRuleProtocolType;
  /**
   * Port number for the protocol, cannot be greater than 64000. This field is optional.
   */
  port?: number;
}

/**
 * Properties of an application rule.
 */
export interface AzureFirewallApplicationRule {
  /**
   * Name of the application rule.
   */
  name?: string;
  /**
   * Description of the rule.
   */
  description?: string;
  /**
   * List of source IP addresses for this rule.
   */
  sourceAddresses?: string[];
  /**
   * Array of ApplicationRuleProtocols.
   */
  protocols?: AzureFirewallApplicationRuleProtocol[];
  /**
   * List of FQDNs for this rule.
   */
  targetFqdns?: string[];
  /**
   * List of FQDN Tags for this rule.
   */
  fqdnTags?: string[];
  /**
   * List of source IpGroups for this rule.
   */
  sourceIpGroups?: string[];
}

/**
 * Application rule collection resource.
 */
export interface AzureFirewallApplicationRuleCollection extends SubResource {
  /**
   * Priority of the application rule collection resource.
   */
  priority?: number;
  /**
   * The action type of a rule collection.
   */
  action?: AzureFirewallRCAction;
  /**
   * Collection of rules used by a application rule collection.
   */
  rules?: AzureFirewallApplicationRule[];
  /**
   * The provisioning state of the application rule collection resource. Possible values include:
   * 'Succeeded', 'Updating', 'Deleting', 'Failed'
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly provisioningState?: ProvisioningState;
  /**
   * The name of the resource that is unique within the Azure firewall. This name can be used to
   * access the resource.
   */
  name?: string;
  /**
   * A unique read-only string that changes whenever the resource is updated.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly etag?: string;
}

/**
 * AzureFirewall NAT Rule Collection Action.
 */
export interface AzureFirewallNatRCAction {
  /**
   * The type of action. Possible values include: 'Snat', 'Dnat'
   */
  type?: AzureFirewallNatRCActionType;
}

/**
 * Properties of a NAT rule.
 */
export interface AzureFirewallNatRule {
  /**
   * Name of the NAT rule.
   */
  name?: string;
  /**
   * Description of the rule.
   */
  description?: string;
  /**
   * List of source IP addresses for this rule.
   */
  sourceAddresses?: string[];
  /**
   * List of destination IP addresses for this rule. Supports IP ranges, prefixes, and service
   * tags.
   */
  destinationAddresses?: string[];
  /**
   * List of destination ports.
   */
  destinationPorts?: string[];
  /**
   * Array of AzureFirewallNetworkRuleProtocols applicable to this NAT rule.
   */
  protocols?: AzureFirewallNetworkRuleProtocol[];
  /**
   * The translated address for this NAT rule.
   */
  translatedAddress?: string;
  /**
   * The translated port for this NAT rule.
   */
  translatedPort?: string;
  /**
   * The translated FQDN for this NAT rule.
   */
  translatedFqdn?: string;
  /**
   * List of source IpGroups for this rule.
   */
  sourceIpGroups?: string[];
}

/**
 * NAT rule collection resource.
 */
export interface AzureFirewallNatRuleCollection extends SubResource {
  /**
   * Priority of the NAT rule collection resource.
   */
  priority?: number;
  /**
   * The action type of a NAT rule collection.
   */
  action?: AzureFirewallNatRCAction;
  /**
   * Collection of rules used by a NAT rule collection.
   */
  rules?: AzureFirewallNatRule[];
  /**
   * The provisioning state of the NAT rule collection resource. Possible values include:
   * 'Succeeded', 'Updating', 'Deleting', 'Failed'
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly provisioningState?: ProvisioningState;
  /**
   * The name of the resource that is unique within the Azure firewall. This name can be used to
   * access the resource.
   */
  name?: string;
  /**
   * A unique read-only string that changes whenever the resource is updated.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly etag?: string;
}

/**
 * Properties of the network rule.
 */
export interface AzureFirewallNetworkRule {
  /**
   * Name of the network rule.
   */
  name?: string;
  /**
   * Description of the rule.
   */
  description?: string;
  /**
   * Array of AzureFirewallNetworkRuleProtocols.
   */
  protocols?: AzureFirewallNetworkRuleProtocol[];
  /**
   * List of source IP addresses for this rule.
   */
  sourceAddresses?: string[];
  /**
   * List of destination IP addresses.
   */
  destinationAddresses?: string[];
  /**
   * List of destination ports.
   */
  destinationPorts?: string[];
  /**
   * List of destination FQDNs.
   */
  destinationFqdns?: string[];
  /**
   * List of source IpGroups for this rule.
   */
  sourceIpGroups?: string[];
  /**
   * List of destination IpGroups for this rule.
   */
  destinationIpGroups?: string[];
}

/**
 * Network rule collection resource.
 */
export interface AzureFirewallNetworkRuleCollection extends SubResource {
  /**
   * Priority of the network rule collection resource.
   */
  priority?: number;
  /**
   * The action type of a rule collection.
   */
  action?: AzureFirewallRCAction;
  /**
   * Collection of rules used by a network rule collection.
   */
  rules?: AzureFirewallNetworkRule[];
  /**
   * The provisioning state of the network rule collection resource. Possible values include:
   * 'Succeeded', 'Updating', 'Deleting', 'Failed'
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly provisioningState?: ProvisioningState;
  /**
   * The name of the resource that is unique within the Azure firewall. This name can be used to
   * access the resource.
   */
  name?: string;
  /**
   * A unique read-only string that changes whenever the resource is updated.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly etag?: string;
}

/**
 * SKU of an Azure Firewall.
 */
export interface AzureFirewallSku {
  /**
   * Name of an Azure Firewall SKU. Possible values include: 'AZFW_VNet', 'AZFW_Hub'
   */
  name?: AzureFirewallSkuName;
  /**
   * Tier of an Azure Firewall. Possible values include: 'Standard', 'Premium'
   */
  tier?: AzureFirewallSkuTier;
}

/**
 * Common resource representation.
 */
export interface Resource {
  /**
   * Resource ID.
   */
  id?: string;
  /**
   * Resource name.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly name?: string;
  /**
   * Resource type.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly type?: string;
  /**
   * Resource location.
   */
  location?: string;
  /**
   * Resource tags.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * Azure Firewall resource.
 */
export interface AzureFirewall extends Resource {
  /**
   * Collection of application rule collections used by Azure Firewall.
   */
  applicationRuleCollections?: AzureFirewallApplicationRuleCollection[];
  /**
   * Collection of NAT rule collections used by Azure Firewall.
   */
  natRuleCollections?: AzureFirewallNatRuleCollection[];
  /**
   * Collection of network rule collections used by Azure Firewall.
   */
  networkRuleCollections?: AzureFirewallNetworkRuleCollection[];
  /**
   * IP configuration of the Azure Firewall resource.
   */
  ipConfigurations?: AzureFirewallIPConfiguration[];
  /**
   * IP configuration of the Azure Firewall used for management traffic.
   */
  managementIpConfiguration?: AzureFirewallIPConfiguration;
  /**
   * The provisioning state of the Azure firewall resource. Possible values include: 'Succeeded',
   * 'Updating', 'Deleting', 'Failed'
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly provisioningState?: ProvisioningState;
  /**
   * The operation mode for Threat Intelligence. Possible values include: 'Alert', 'Deny', 'Off'
   */
  threatIntelMode?: AzureFirewallThreatIntelMode;
  /**
   * The virtualHub to which the firewall belongs.
   */
  virtualHub?: SubResource;
  /**
   * The firewallPolicy associated with this azure firewall.
   */
  firewallPolicy?: SubResource;
  /**
   * IP addresses associated with AzureFirewall.
   */
  hubIPAddresses?: HubIPAddresses;
  /**
   * IpGroups associated with AzureFirewall.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly ipGroups?: AzureFirewallIpGroups[];
  /**
   * The Azure Firewall Resource SKU.
   */
  sku?: AzureFirewallSku;
  /**
   * The additional properties used to further config this azure firewall.
   */
  additionalProperties?: { [propertyName: string]: string };
  /**
   * A list of availability zones denoting where the resource needs to come from.
   */
  zones?: string[];
  /**
   * A unique read-only string that changes whenever the resource is updated.
   * **NOTE: This property will not be serialized. It can only be populated by the server.**
   */
  readonly etag?: string;
}

/**
 * Response for ListAzureFirewalls API service call.
 */
export interface AzureFirewallListResult {
  /**
   * List of Azure Firewalls in a resource group.
   */
  value?: AzureFirewall[];
  /**
   * URL to get the next set of results.
   */
  nextLink?: string;
}

/**
 * An error response from the service.
 */
export interface CloudErrorBody {
  /**
   * An identifier for the error. Codes are invariant and are intended to be consumed
   * programmatically.
   */
  code?: string;
  /**
   * A message describing the error, intended to be suitable for display in a user interface.
   */
  message?: string;
  /**
   * The target of the particular error. For example, the name of the property in error.
   */
  target?: string;
  /**
   * A list of additional details about the error.
   */
  details?: CloudErrorBody[];
}

/**
 * An error response from the service.
 */
export interface CloudError {
  /**
   * Cloud error body.
   */
  error?: CloudErrorBody;
}

/**
 * Tags object for patch operations.
 */
export interface TagsObject {
  /**
   * Resource tags.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * An interface representing NetworkManagementClientOptions.
 */
export interface NetworkManagementClientOptions extends ServiceClientOptions {
  baseUri?: string;
}

/**
 * Defines values for ProvisioningState.
 * Possible values include: 'Succeeded', 'Updating', 'Deleting', 'Failed'
 * @readonly
 * @enum {string}
 */
export enum ProvisioningState {
  Succeeded = 'Succeeded',
  Updating = 'Updating',
  Deleting = 'Deleting',
  Failed = 'Failed',
}

/**
 * Defines values for AzureFirewallRCActionType.
 * Possible values include: 'Allow', 'Deny'
 * @readonly
 * @enum {string}
 */
export enum AzureFirewallRCActionType {
  Allow = 'Allow',
  Deny = 'Deny',
}

/**
 * Defines values for AzureFirewallApplicationRuleProtocolType.
 * Possible values include: 'Http', 'Https', 'Mssql'
 * @readonly
 * @enum {string}
 */
export enum AzureFirewallApplicationRuleProtocolType {
  Http = 'Http',
  Https = 'Https',
  Mssql = 'Mssql',
}

/**
 * Defines values for AzureFirewallNatRCActionType.
 * Possible values include: 'Snat', 'Dnat'
 * @readonly
 * @enum {string}
 */
export enum AzureFirewallNatRCActionType {
  Snat = 'Snat',
  Dnat = 'Dnat',
}

/**
 * Defines values for AzureFirewallNetworkRuleProtocol.
 * Possible values include: 'TCP', 'UDP', 'Any', 'ICMP'
 * @readonly
 * @enum {string}
 */
export enum AzureFirewallNetworkRuleProtocol {
  TCP = 'TCP',
  UDP = 'UDP',
  Any = 'Any',
  ICMP = 'ICMP',
}

/**
 * Defines values for AzureFirewallThreatIntelMode.
 * Possible values include: 'Alert', 'Deny', 'Off'
 * @readonly
 * @enum {string}
 */
export enum AzureFirewallThreatIntelMode {
  Alert = 'Alert',
  Deny = 'Deny',
  Off = 'Off',
}

/**
 * Defines values for AzureFirewallSkuName.
 * Possible values include: 'AZFW_VNet', 'AZFW_Hub'
 * @readonly
 * @enum {string}
 */
export enum AzureFirewallSkuName {
  AZFWVNet = 'AZFW_VNet',
  AZFWHub = 'AZFW_Hub',
}

/**
 * Defines values for AzureFirewallSkuTier.
 * Possible values include: 'Standard', 'Premium'
 * @readonly
 * @enum {string}
 */
export enum AzureFirewallSkuTier {
  Standard = 'Standard',
  Premium = 'Premium',
}

/**
 * Contains response data for the get operation.
 */
export type AzureFirewallsGetResponse = AzureFirewall & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: AzureFirewall;
    };
};

/**
 * Contains response data for the createOrUpdate operation.
 */
export type AzureFirewallsCreateOrUpdateResponse = AzureFirewall & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: AzureFirewall;
    };
};

/**
 * Contains response data for the updateTags operation.
 */
export type AzureFirewallsUpdateTagsResponse = AzureFirewall & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: AzureFirewall;
    };
};

/**
 * Contains response data for the list operation.
 */
export type AzureFirewallsListResponse = AzureFirewallListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: AzureFirewallListResult;
    };
};

/**
 * Contains response data for the listAll operation.
 */
export type AzureFirewallsListAllResponse = AzureFirewallListResult & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;

      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: AzureFirewallListResult;
    };
};
