/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { NetworkManagementClientContext } from "./networkManagementClientContext";

class NetworkManagementClient extends NetworkManagementClientContext {
  // Operation groups
  azureFirewalls: operations.AzureFirewalls;

  /**
   * Initializes a new instance of the NetworkManagementClient class.
   * @param subscriptionId The subscription credentials which uniquely identify the Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param apiVersion Client API version.
   * @param [options] The parameter options
   */
  constructor(subscriptionId: string, apiVersion: string, options?: Models.NetworkManagementClientOptions) {
    super(subscriptionId, apiVersion, options);
    this.azureFirewalls = new operations.AzureFirewalls(this);
  }
}

// Operation Specifications

export {
  NetworkManagementClient,
  NetworkManagementClientContext,
  Models as NetworkManagementModels,
  Mappers as NetworkManagementMappers
};
export * from "./operations";
