/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "./models";

const packageName = "azureFirewall";
const packageVersion = "1.0.0";

export class NetworkManagementClientContext extends msRest.ServiceClient {
  subscriptionId: string;
  apiVersion: string;

  /**
   * Initializes a new instance of the NetworkManagementClientContext class.
   * @param subscriptionId The subscription credentials which uniquely identify the Microsoft Azure
   * subscription. The subscription ID forms part of the URI for every service call.
   * @param apiVersion Client API version.
   * @param [options] The parameter options
   */
  constructor(subscriptionId: string, apiVersion: string, options?: Models.NetworkManagementClientOptions) {
    if (subscriptionId == undefined) {
      throw new Error("'subscriptionId' cannot be null.");
    }
    if (apiVersion == undefined) {
      throw new Error("'apiVersion' cannot be null.");
    }

    if (!options) {
      options = {};
    }

    if (!options.userAgent) {
      const defaultUserAgent = msRest.getDefaultUserAgentValue();
      options.userAgent = `${packageName}/${packageVersion} ${defaultUserAgent}`;
    }

    super(undefined, options);

    this.baseUri = options.baseUri || this.baseUri || "https://management.azure.com";
    this.requestContentType = "application/json; charset=utf-8";
    this.subscriptionId = subscriptionId;
    this.apiVersion = apiVersion;
  }
}
